apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebAPIDockerDemo
  template:
    metadata:
      labels:
        app: WebAPIDockerDemo
    spec:
      containers:
      - name: dockersamplerepos
        image: 856720cr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: webapidockerdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebAPIDockerDemo